const std = @import("std");
const inspect = @import("inspect.zig");

/// Write deterministic Zig structs for tables in a schema artifact.
/// Names are sanitized to Zig identifiers; SQL names remain in comments.
pub fn writeStructs(writer: *std.Io.Writer, schema: inspect.Schema) !void {
    try writer.writeAll(
        "// Generated by zsql gen structs. Do not edit manually.\n" ++
            "const zsql = @import(\"zsql\");\n\n",
    );
    for (schema.tables, 0..) |table, table_index| {
        try writer.writeAll("pub const ");
        try writeTableTypeIdent(writer, table);
        const collision_ordinal = typeIdentCollisionOrdinal(schema.tables[0..table_index], table);
        if (collision_ordinal != 1) try writer.print("_{d}", .{collision_ordinal});
        try writer.writeAll(" = struct {\n");
        for (table.columns) |column| {
            try writer.writeAll("    ");
            try writeFieldIdent(writer, column.name);
            try writer.writeAll(": ");
            if (column.nullable) try writer.writeByte('?');
            try writer.print("{s},\n", .{zigType(column.type_name)});
        }
        try writer.writeAll("};\n\n");
    }
}

fn zigType(sql_type: []const u8) []const u8 {
    if (eq(sql_type, "bool") or eq(sql_type, "boolean")) return "bool";
    if (eq(sql_type, "int2")) return "i16";
    if (eq(sql_type, "int4")) return "i32";
    if (eq(sql_type, "int8") or eq(sql_type, "bigint")) return "i64";
    // SQLite affinity names do not constrain stored integer/real width. Its
    // driver exposes i64/f64, so generated structs use the non-narrowing type.
    if (eq(sql_type, "smallint") or eq(sql_type, "integer") or eq(sql_type, "int") or eq(sql_type, "serial") or eq(sql_type, "bigserial")) return "i64";
    if (eq(sql_type, "float4")) return "f32";
    if (eq(sql_type, "real") or eq(sql_type, "float")) return "f64";
    if (eq(sql_type, "float8") or eq(sql_type, "double precision")) return "f64";
    if (eq(sql_type, "uuid")) return "zsql.types.Uuid";
    if (eq(sql_type, "numeric") or eq(sql_type, "decimal")) return "zsql.types.Numeric";
    if (eq(sql_type, "bytea") or eq(sql_type, "blob")) return "zsql.types.Blob";
    return "[]const u8";
}

fn eq(a: []const u8, b: []const u8) bool {
    return std.ascii.eqlIgnoreCase(a, b);
}

fn writeTypeIdent(writer: *std.Io.Writer, name: []const u8) !void {
    var it = TypeIdentIterator.init(name);
    while (it.next()) |byte| try writer.writeByte(byte);
}

fn writeTableTypeIdent(writer: *std.Io.Writer, table: inspect.Table) !void {
    if (table.schema) |schema_name| {
        if (!std.mem.eql(u8, schema_name, "public")) try writeTypeIdent(writer, schema_name);
    }
    try writeTypeIdent(writer, table.name);
}

fn writeFieldIdent(writer: *std.Io.Writer, name: []const u8) !void {
    try writer.print("{f}", .{std.zig.fmtId(name)});
}

/// Existing type names stay ergonomic (`user_profiles` -> `UserProfiles`).
/// Invalid leading digits receive a `Table` prefix, and callers append a
/// deterministic ordinal when two SQL names normalize to the same Zig name.
const TypeIdentIterator = struct {
    name: []const u8,
    index: usize = 0,
    prefix_index: usize = 0,
    needs_prefix: bool,
    upper: bool = true,

    fn init(name: []const u8) TypeIdentIterator {
        var first: ?u8 = null;
        for (name) |byte| {
            if (std.ascii.isAlphanumeric(byte)) {
                first = byte;
                break;
            }
        }
        return .{ .name = name, .needs_prefix = first == null or std.ascii.isDigit(first.?) };
    }

    fn next(self: *TypeIdentIterator) ?u8 {
        const prefix = "Table";
        if (self.needs_prefix and self.prefix_index < prefix.len) {
            defer self.prefix_index += 1;
            return prefix[self.prefix_index];
        }
        while (self.index < self.name.len) {
            const byte = self.name[self.index];
            self.index += 1;
            if (!std.ascii.isAlphanumeric(byte)) {
                self.upper = true;
                continue;
            }
            const result = if (self.upper) std.ascii.toUpper(byte) else byte;
            self.upper = false;
            return result;
        }
        return null;
    }
};

fn sameTypeIdent(a: []const u8, b: []const u8) bool {
    var left = TypeIdentIterator.init(a);
    var right = TypeIdentIterator.init(b);
    while (true) {
        const left_byte = left.next();
        const right_byte = right.next();
        if (left_byte != right_byte) return false;
        if (left_byte == null) return true;
    }
}

fn sameTableTypeIdent(a: inspect.Table, b: inspect.Table) bool {
    const a_schema = if (a.schema) |name| if (!std.mem.eql(u8, name, "public")) name else null else null;
    const b_schema = if (b.schema) |name| if (!std.mem.eql(u8, name, "public")) name else null else null;
    if (a_schema != null or b_schema != null) {
        if (a_schema == null or b_schema == null) return false;
        if (!sameTypeIdent(a_schema.?, b_schema.?)) return false;
    }
    return sameTypeIdent(a.name, b.name);
}

fn typeIdentCollisionOrdinal(previous: []const inspect.Table, table: inspect.Table) usize {
    var ordinal: usize = 1;
    for (previous) |candidate| {
        if (sameTableTypeIdent(candidate, table)) ordinal += 1;
    }
    return ordinal;
}

test "writeStructs qualifies non-public PostgreSQL table types" {
    const schema = inspect.Schema{ .dialect = .postgres, .tables = &.{
        .{ .schema = "public", .name = "events", .columns = &.{} },
        .{ .schema = "audit", .name = "events", .columns = &.{} },
        .{ .schema = "reporting", .name = "events", .columns = &.{} },
    } };
    var buffer: [512]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buffer);
    try writeStructs(&writer, schema);
    try std.testing.expectEqualStrings(
        "// Generated by zsql gen structs. Do not edit manually.\nconst zsql = @import(\"zsql\");\n\npub const Events = struct {\n};\n\npub const AuditEvents = struct {\n};\n\npub const ReportingEvents = struct {\n};\n\n",
        writer.buffered(),
    );
}

test "writeStructs maps common schema types" {
    const schema = inspect.Schema{ .tables = &.{.{ .name = "user_profiles", .columns = &.{
        .{ .name = "id", .type_name = "int8", .nullable = false },
        .{ .name = "is-active", .type_name = "boolean", .nullable = false },
        .{ .name = "avatar", .type_name = "bytea", .nullable = true },
        .{ .name = "balance", .type_name = "numeric", .nullable = false },
        .{ .name = "external_id", .type_name = "uuid", .nullable = false },
    } }} };
    var buffer: [1024]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buffer);
    try writeStructs(&writer, schema);
    try std.testing.expectEqualStrings(
        "// Generated by zsql gen structs. Do not edit manually.\nconst zsql = @import(\"zsql\");\n\npub const UserProfiles = struct {\n    id: i64,\n    @\"is-active\": bool,\n    avatar: ?zsql.types.Blob,\n    balance: zsql.types.Numeric,\n    external_id: zsql.types.Uuid,\n};\n\n",
        writer.buffered(),
    );

    const source = try std.testing.allocator.dupeZ(u8, writer.buffered());
    defer std.testing.allocator.free(source);
    var ast = try std.zig.Ast.parse(std.testing.allocator, source, .zig);
    defer ast.deinit(std.testing.allocator);
    try std.testing.expectEqual(@as(usize, 0), ast.errors.len);
}

test "writeStructs emits valid exact fields and collision-free table names" {
    const schema = inspect.Schema{ .tables = &.{
        .{ .name = "123 users", .columns = &.{
            .{ .name = "type", .type_name = "text", .nullable = false },
            .{ .name = "1st-value", .type_name = "integer", .nullable = true },
            .{ .name = "score", .type_name = "real", .nullable = false },
        } },
        .{ .name = "123-users", .columns = &.{
            .{ .name = "line\nbreak", .type_name = "text", .nullable = false },
        } },
    } };
    var buffer: [1024]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buffer);
    try writeStructs(&writer, schema);
    try std.testing.expectEqualStrings(
        "// Generated by zsql gen structs. Do not edit manually.\nconst zsql = @import(\"zsql\");\n\npub const Table123Users = struct {\n    @\"type\": []const u8,\n    @\"1st-value\": ?i64,\n    score: f64,\n};\n\npub const Table123Users_2 = struct {\n    @\"line\\nbreak\": []const u8,\n};\n\n",
        writer.buffered(),
    );

    const source = try std.testing.allocator.dupeZ(u8, writer.buffered());
    defer std.testing.allocator.free(source);
    var ast = try std.zig.Ast.parse(std.testing.allocator, source, .zig);
    defer ast.deinit(std.testing.allocator);
    try std.testing.expectEqual(@as(usize, 0), ast.errors.len);
}
