const std = @import("std");
const inspect = @import("inspect.zig");

/// Write deterministic Zig structs for tables in a schema artifact.
/// Names are sanitized to Zig identifiers; SQL names remain in comments.
pub fn writeStructs(writer: *std.Io.Writer, schema: inspect.Schema) !void {
    try writer.writeAll("// Generated by zsql gen structs. Do not edit manually.\n\n");
    for (schema.tables) |table| {
        try writer.writeAll("pub const ");
        try writeTypeIdent(writer, table.name);
        try writer.writeAll(" = struct {\n");
        for (table.columns) |column| {
            try writer.writeAll("    ");
            try writeFieldIdent(writer, column.name);
            try writer.print(": {s}, // SQL: {s}\n", .{ zigType(column.type_name), column.name });
        }
        try writer.writeAll("};\n\n");
    }
}

fn zigType(sql_type: []const u8) []const u8 {
    if (eq(sql_type, "bool") or eq(sql_type, "boolean")) return "bool";
    if (eq(sql_type, "int2") or eq(sql_type, "smallint")) return "i16";
    if (eq(sql_type, "int4") or eq(sql_type, "integer") or eq(sql_type, "int")) return "i32";
    if (eq(sql_type, "int8") or eq(sql_type, "bigint")) return "i64";
    if (eq(sql_type, "float4") or eq(sql_type, "real")) return "f32";
    if (eq(sql_type, "float8") or eq(sql_type, "double precision")) return "f64";
    if (eq(sql_type, "uuid")) return "zsql.types.Uuid";
    if (eq(sql_type, "numeric") or eq(sql_type, "decimal")) return "zsql.types.Numeric";
    if (eq(sql_type, "bytea") or eq(sql_type, "blob")) return "zsql.types.Blob";
    return "[]const u8";
}

fn eq(a: []const u8, b: []const u8) bool {
    return std.ascii.eqlIgnoreCase(a, b);
}

fn writeTypeIdent(writer: *std.Io.Writer, name: []const u8) !void {
    var upper = true;
    for (name) |c| {
        if (std.ascii.isAlphanumeric(c)) {
            try writer.writeByte(if (upper) std.ascii.toUpper(c) else c);
            upper = false;
        } else upper = true;
    }
    if (name.len == 0) try writer.writeAll("Table");
}

fn writeFieldIdent(writer: *std.Io.Writer, name: []const u8) !void {
    if (name.len == 0 or std.ascii.isDigit(name[0])) try writer.writeByte('_');
    for (name) |c| try writer.writeByte(if (std.ascii.isAlphanumeric(c) or c == '_') c else '_');
}

test "writeStructs maps common schema types" {
    const schema = inspect.Schema{ .tables = &.{.{ .name = "user_profiles", .columns = &.{
        .{ .name = "id", .type_name = "int8", .nullable = false },
        .{ .name = "is-active", .type_name = "boolean", .nullable = false },
        .{ .name = "avatar", .type_name = "bytea", .nullable = true },
    } }} };
    var buffer: [1024]u8 = undefined;
    var writer = std.Io.Writer.fixed(&buffer);
    try writeStructs(&writer, schema);
    try std.testing.expectEqualStrings(
        "// Generated by zsql gen structs. Do not edit manually.\n\npub const UserProfiles = struct {\n    id: i64, // SQL: id\n    is_active: bool, // SQL: is-active\n    avatar: zsql.types.Blob, // SQL: avatar\n};\n\n",
        writer.buffered(),
    );
}
