pub const Error = error{
    DriverUnavailable,
    DriverError,
    InvalidColumn,
    InvalidColumnType,
    InvalidBindValue,
    InvalidSql,
    InvalidMigrationFilename,
    UnexpectedRow,
    StatementClosed,
    ConnectionClosed,
    TransactionClosed,
    SavepointClosed,
    PoolClosed,
    PoolExhausted,
    LeaseClosed,
    OutOfMemory,
};
