pub const Error = error{
    DriverUnavailable,
    DriverError,
    InvalidColumn,
    InvalidColumnType,
    TypeMismatch,
    UnexpectedNull,
    IntegerOverflow,
    InvalidBindValue,
    /// Positional/named bind slice length does not match the statement.
    BindCountMismatch,
    InvalidSql,
    InvalidUrl,
    InvalidArguments,
    NoRows,
    TooManyRows,
    InvalidMigrationFilename,
    /// Two migration files use the same version.
    MigrationVersionConflict,
    /// Backward-compatible spelling; new APIs return `MigrationVersionConflict`.
    DuplicateMigrationVersion,
    MigrationChecksumMismatch,
    /// Migration history contains a dirty/incomplete entry and needs repair.
    MigrationDirty,
    MigrationNotFound,
    MigrationNotDirty,
    /// Backward-compatible spelling; new APIs return `MigrationDirty`.
    DirtyMigration,
    UnexpectedRow,
    StatementClosed,
    ConnectionClosed,
    ConnectionBusy,
    ConnectionTimeout,
    /// Statement or query exceeded a driver/server timeout (when reported).
    QueryTimeout,
    TransactionClosed,
    /// PostgreSQL transaction is in failed state and must be rolled back.
    TransactionAborted,
    SavepointClosed,
    PoolClosed,
    PoolExhausted,
    PoolTimeout,
    LeaseClosed,
    AuthFailed,
    TlsFailed,
    ProtocolError,
    ConstraintViolation,
    UniqueViolation,
    ForeignKeyViolation,
    NotNullViolation,
    CheckViolation,
    SerializationFailure,
    DeadlockDetected,
    Busy,
    Locked,
    Unsupported,
    OutOfMemory,
};
