#!/usr/bin/env python3
"""Generate compact Unicode 3.2 tables for PostgreSQL-compatible SASLprep."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import struct
import stringprep
import sys
import unicodedata


ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "src/drivers/postgres/saslprep_tables.zig"
UCD = unicodedata.ucd_3_2_0
MAX_CODEPOINT = 0x110000


def codepoint_ranges(predicate):
    result = []
    start = None
    previous = None
    for codepoint in range(MAX_CODEPOINT):
        if predicate(chr(codepoint)):
            if start is None:
                start = codepoint
            previous = codepoint
        elif start is not None:
            result.append((start, previous))
            start = None
    if start is not None:
        result.append((start, previous))
    return result


def union_predicate(*predicates):
    return lambda character: any(predicate(character) for predicate in predicates)


def emit_array(lines, declaration, item_type, items, formatter):
    lines.append(f"pub const {declaration} = [_]{item_type}{{")
    lines.extend(f"    {formatter(item)}," for item in items)
    lines.append("};")
    lines.append("")


def generate() -> str:
    range_tables = {
        "nfkc_changed": codepoint_ranges(
            lambda character: UCD.normalize("NFKC", character) != character
        ),
        "non_ascii_space": codepoint_ranges(stringprep.in_table_c12),
        "mapped_to_nothing": codepoint_ranges(stringprep.in_table_b1),
        "prohibited": codepoint_ranges(
            union_predicate(
                stringprep.in_table_c21,
                stringprep.in_table_c22,
                stringprep.in_table_c3,
                stringprep.in_table_c4,
                stringprep.in_table_c5,
                stringprep.in_table_c6,
                stringprep.in_table_c7,
                stringprep.in_table_c8,
                stringprep.in_table_c9,
            )
        ),
        "unassigned": codepoint_ranges(stringprep.in_table_a1),
        "randal": codepoint_ranges(stringprep.in_table_d1),
        "lcat": codepoint_ranges(stringprep.in_table_d2),
    }

    decomposition_entries = []
    decomposition_scalars = []
    combining_classes = []
    compositions = []
    nfkc_changed = hashlib.sha256()

    for codepoint in range(MAX_CODEPOINT):
        character = chr(codepoint)
        combining_class = UCD.combining(character)
        if combining_class:
            combining_classes.append((codepoint, combining_class))

        # Hangul syllables are decomposed and composed algorithmically.
        normalized = UCD.normalize("NFKD", character)
        if normalized != character and not 0xAC00 <= codepoint <= 0xD7A3:
            offset = len(decomposition_scalars)
            scalars = [ord(item) for item in normalized]
            decomposition_scalars.extend(scalars)
            decomposition_entries.append((codepoint, offset, len(scalars)))

        nfkc = UCD.normalize("NFKC", character)
        if nfkc != character:
            encoded = nfkc.encode("utf-8")
            nfkc_changed.update(struct.pack(">II", codepoint, len(encoded)))
            nfkc_changed.update(encoded)

        canonical = UCD.decomposition(character)
        if canonical and not canonical.startswith("<"):
            pair = [int(item, 16) for item in canonical.split()]
            if len(pair) == 2 and UCD.normalize("NFC", "".join(map(chr, pair))) == character:
                compositions.append((pair[0], pair[1], codepoint))

    compositions.sort(key=lambda item: (item[0], item[1]))

    lines = [
        "// Generated by scripts/generate_saslprep_tables.py; do not edit.",
        "// Unicode data is frozen at version 3.2 as required by RFC 3454/4013.",
        "",
        "pub const Range = struct { first: u21, last: u21 };",
        "pub const Decomposition = struct { codepoint: u21, offset: u32, len: u8 };",
        "pub const CombiningClass = struct { codepoint: u21, class: u8 };",
        "pub const Composition = struct { first: u21, second: u21, composed: u21 };",
        "",
        "pub const nfkc_changed_sha256 = [32]u8{ " +
        ", ".join(f"0x{byte:02x}" for byte in nfkc_changed.digest()) + " };",
        "",
    ]

    for name, ranges in range_tables.items():
        emit_array(
            lines,
            f"{name}_ranges",
            "Range",
            ranges,
            lambda item: f".{{ .first = 0x{item[0]:x}, .last = 0x{item[1]:x} }}",
        )

    emit_array(
        lines,
        "decompositions",
        "Decomposition",
        decomposition_entries,
        lambda item: (
            f".{{ .codepoint = 0x{item[0]:x}, .offset = {item[1]}, .len = {item[2]} }}"
        ),
    )
    emit_array(
        lines,
        "decomposition_scalars",
        "u21",
        decomposition_scalars,
        lambda item: f"0x{item:x}",
    )
    emit_array(
        lines,
        "combining_classes",
        "CombiningClass",
        combining_classes,
        lambda item: f".{{ .codepoint = 0x{item[0]:x}, .class = {item[1]} }}",
    )
    emit_array(
        lines,
        "compositions",
        "Composition",
        compositions,
        lambda item: (
            f".{{ .first = 0x{item[0]:x}, .second = 0x{item[1]:x}, .composed = 0x{item[2]:x} }}"
        ),
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    rendered = generate()
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated table: {args.output}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"stale generated table: run {pathlib.Path(__file__).name}",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
